"""D7's simple cases stay as they were (2026-10-09): a version whose rows all came from sources,
and a version derived from one, are green on C-4 and C-6, and the record says no row was generated.
The derived version's record names its ancestor beside "Rows dropped by step"."""

from __future__ import annotations

import json
from pathlib import Path

import httpx

from src.core.database import sync_session_factory
from src.models import Job, Version
from tests.support.publish_fixtures import (
    REPO,
    PublishDriver,
    built_version,
    completed_build,
    publish_and_run,
    publisher,
    store_token,
)
from tests.support.stub_operators import body
from tests.support.version_fixtures import BuildDriver, driver

__all__ = ["driver", "publisher"]


def line(record: str, check: str) -> str:
    return next(x for x in record.splitlines() if x.startswith(f"- {check} "))


async def record_of(client: httpx.AsyncClient, publisher: PublishDriver, version_id: str) -> str:
    await completed_build(client, publisher, version_id)
    draft = await client.get(f"/api/v1/versions/{version_id}/card-draft")
    assert draft.status_code == 200, draft.text
    return str(draft.json()["record_markdown"])


async def test_a_sources_only_version_is_green_and_generated_nothing(
    client: httpx.AsyncClient,
    operator_name: str,
    driver: BuildDriver,
    publisher: PublishDriver,
    data_dir: Path,
) -> None:
    version_id = await built_version(client, driver, data_dir)
    record = await record_of(client, publisher, version_id)
    assert line(record, "C-4") == (
        "- C-4 green: No model labelled or generated rows in this version or its lineage."
    )
    assert line(record, "C-6") == (
        "- C-6 green: No model labeler produced labels in this version or its lineage."
    )
    assert "No model labeler; labels, if any, came with the sources." in record
    assert "No row was generated by a model." in record
    assert "covers this version's own steps only" not in record
    manifest = (await client.get(f"/api/v1/versions/{version_id}/handoff-manifest")).json()
    assert manifest["extensions"]["lineage"] == {
        "ancestor_versions": [],
        "generated_rows": 0,
        "generators": [],
    }


async def derived_version(
    client: httpx.AsyncClient, driver: BuildDriver, data_dir: Path
) -> tuple[str, str, int]:
    """(parent, child, parent number): a version built from a sources-only version."""
    parent = await built_version(client, driver, data_dir)
    with sync_session_factory()() as db:
        row = db.get(Version, parent)
        assert row is not None
        dataset_id, number = str(row.dataset_id), int(row.number)
    rec = await client.post(
        "/api/v1/recipes", json={"name": "keep-r", "body": body(("stub_keep", {}))}
    )
    assert rec.status_code == 201, rec.text
    response = await client.post(
        "/api/v1/versions",
        json={
            "dataset_id": dataset_id,
            "recipe_revision_id": rec.json()["head_revision_id"],
            "inputs": [{"kind": "version", "version_id": parent}],
        },
    )
    assert response.status_code == 202, response.text
    job_id = response.json()["job_id"]
    assert driver.run(job_id) == "completed"
    with sync_session_factory()() as db:
        job = db.get(Job, job_id)
        assert job is not None and job.result is not None
        return parent, str(job.result["version_id"]), number


async def test_a_derived_sources_only_version_names_its_ancestor_and_stays_green(
    client: httpx.AsyncClient,
    operator_name: str,
    driver: BuildDriver,
    publisher: PublishDriver,
    data_dir: Path,
) -> None:
    parent, child, number = await derived_version(client, driver, data_dir)
    record = await record_of(client, publisher, child)
    assert line(record, "C-4").startswith("- C-4 green:")
    assert line(record, "C-6").startswith("- C-6 green:")
    assert f"v{number} (`{parent}`)" in record.split("### Rows dropped by step", 1)[1]


async def test_the_published_card_and_manifest_carry_the_lineage(
    client: httpx.AsyncClient,
    operator_name: str,
    driver: BuildDriver,
    publisher: PublishDriver,
    data_dir: Path,
) -> None:
    """The publish worker renders its own card (not the draft's): the lineage reaches it too."""
    await store_token(client)
    parent, child, number = await derived_version(client, driver, data_dir)
    build = await completed_build(client, publisher, child)
    pub = await publish_and_run(client, publisher, child, build["id"])
    assert pub["status"] == "published", pub["error"]
    files = publisher.hub.head_files(REPO)
    readme = files["README.md"].decode()
    assert "### Generated rows" in readme and "No row was generated by a model." in readme
    assert f"v{number} (`{parent}`)" in readme.split("### Rows dropped by step", 1)[1]
    manifest = json.loads(files["midataworks-dataset-version.json"])
    assert manifest["extensions"]["lineage"]["ancestor_versions"] == [
        {"version_id": parent, "number": number}
    ]
