# Origin: miStudio (Onegaishimas/miStudio) backend/src/mcp_server/contract.py @ c829a2cc
# Mode: adapt (docs/REUSE.md). Kept: the contract is DERIVED from the live registry and a test
# regenerates and diffs it; endpoints come from the tool bodies' AST, accepting only paths that
# start with "/". Changed: one registry; a gated column; the "REST contract for proxies" section
# miStudio's dataworks_* proxy relies on (010 FTDD section 5.6).
"""Generate ``docs/mcp-contract.md`` from the LIVE tool registry (FR-010.36).

A hand-maintained contract carried check marks for tools that were never registered, for a whole
increment, in miLLM. This one is regenerated by
``tests/contract/test_mcp_contract_generated.py``, which fails on any difference.

Regenerate::

    cd backend && python -c "from src.mcp_server.contract import write_contract; write_contract()"
"""

from __future__ import annotations

import ast
import asyncio
import inspect
from pathlib import Path
from typing import Any

from .config import MCPSettings
from .context import GATED_TOOLS
from .server import build_server
from .tools import CATEGORY_MODULES

CONTRACT_PATH = Path(__file__).resolve().parents[3] / "docs" / "mcp-contract.md"

HEADER = """<!-- GENERATED FILE: DO NOT EDIT BY HAND.
Regenerate: cd backend && python -c "from src.mcp_server.contract import write_contract; write_contract()"
backend/tests/contract/test_mcp_contract_generated.py fails when this differs from the registry. -->

# miDataworks MCP contract

Every tool the miDataworks MCP server (feature 010) registers, its category, the backend route it
calls and, when an agent calls it, the approval it waits for. Derived from the live registry by
`backend/src/mcp_server/contract.py`.

Agents: call `dataworks_howto` first; it carries the workflow and the result shapes.

Categories are switched by `MCP_TOOL_CATEGORIES`; all eleven are on by default. A category whose
owning feature has not served its routes yet registers no tools (ADR-027); the route ledger in
`backend/tests/support/mcp_ledger.py` lists each pending tool with its feature.
"""

REST_CONTRACT = """## REST contract for proxies

What miStudio's `dataworks_*` proxy (miStudio 034 FR-5 to FR-14) and any other caller rely on
(010 FTDD section 5.6). Additive changes only; checked by
`backend/tests/contract/test_mistudio_proxy_paths_are_served.py`.

| Item | Value |
|---|---|
| Base | Backend under `/api/`, REST under `/api/v1` |
| Health | `GET /api/health`: 200 while the API is up, body `{"status", "dependencies": {name: {"ok", "reason"}}}`; any 2xx is available |
| Success | Plain JSON resources |
| Error | `{"error": {"code", "message", "details"}}` |
| Header | `X-Dataworks-Agent: agent:<name>` (lower case, digits, hyphens; at most 48 characters after `agent:`). This server sends `agent:dataworks-mcp`; miStudio's proxy sends `agent:mistudio-mcp`. A malformed or empty header is refused with `400 INVALID_AGENT_IDENTITY` |
| Pending | `202` with `{"approval_id", "status": "pending", "action", "request_digest", "expires_at", "hint"}` |
| Status | `GET /api/v1/approvals/{id}`: `pending`, `executing`, `executed` (with `result_kind`, `result_id`), `failed` (with `error`), `rejected` (with `reason`), `expired` |
| Refusals | An agent approve or reject is `403 AGENT_CANNOT_DECIDE` |
| Approval actions | `hub_push`, `agent_label_rows`, `version_delete`, `millm_model_load`, `secret_write`, `source_annotate`, `gate_target_write` |
| Counting | The 5,000-row agent labelling window is counted in REST only, per version, never from a caller's number |
| Digest | An approval binds to the exact stored request; a changed request needs a new approval. A send is one approval for the whole send (P-06) |
| Expiry | A pending approval expires after 24 hours |
| OpenAPI | `GET /api/v1/openapi.json` |
"""


def _endpoints(func: ast.AST) -> list[str]:
    """``METHOD /path`` for every client call in a tool body."""
    verbs = {
        "get": "GET",
        "post": "POST",
        "put": "PUT",
        "patch": "PATCH",
        "delete": "DELETE",
        "post_multipart": "POST",
    }
    found: list[str] = []
    for node in ast.walk(func):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)):
            continue
        if node.func.attr not in verbs or not node.args:
            continue
        if not (isinstance(node.func.value, ast.Name) and node.func.value.id == "client"):
            continue
        arg = node.args[0]
        path = None
        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
            path = arg.value
        elif isinstance(arg, ast.JoinedStr):
            path = "".join(
                str(v.value) if isinstance(v, ast.Constant) else "{" + ast.unparse(v.value) + "}"
                for v in arg.values
                if isinstance(v, ast.Constant | ast.FormattedValue)
            )
        if path and path.startswith("/"):
            full = path if path.startswith("/api/") else "/api/v1" + path
            found.append(f"{verbs[node.func.attr]} {full}")
    return sorted(set(found))


def collect() -> dict[str, list[dict[str, Any]]]:
    """``{category: [{name, summary, endpoints, gated}]}``: the registry decides membership."""
    mcp, _ = build_server(
        MCPSettings(auth_token="contract-generation")  # noqa: S106 - never served
    )
    tools = {t.name: t for t in asyncio.run(mcp.list_tools())}
    out: dict[str, list[dict[str, Any]]] = {}
    for category, modules in CATEGORY_MODULES.items():
        rows: list[dict[str, Any]] = []
        for module in modules:
            tree = ast.parse(inspect.getsource(module))
            for node in ast.walk(tree):
                if isinstance(node, ast.AsyncFunctionDef) and node.name in tools:
                    description = (tools[node.name].description or "").strip()
                    rows.append(
                        {
                            "name": node.name,
                            "summary": " ".join(description.split()).split(". ")[0].rstrip(".")
                            + ".",
                            "endpoints": _endpoints(node),
                            "gated": GATED_TOOLS.get(node.name),
                        }
                    )
        out[category] = rows
    return out


def generate_contract() -> str:
    data = collect()
    total = sum(len(rows) for rows in data.values())
    lines = [HEADER, f"**{total} tools in {len(data)} categories.**\n"]
    for category, rows in data.items():
        lines.append(f"## `{category}` ({len(rows)})\n")
        if not rows:
            lines.append("No tools yet: every route this category calls waits on its feature.\n")
            continue
        lines.append("| Tool | Calls | Waits for | What it does |")
        lines.append("|---|---|---|---|")
        for row in rows:
            calls = (
                "<br>".join(f"`{e}`" for e in row["endpoints"]) or "none (served by the MCP server)"
            )
            gated = f"`{row['gated']}`" if row["gated"] else ""
            summary = row["summary"].replace("|", "\\|")
            lines.append(f"| `{row['name']}` | {calls} | {gated} | {summary} |")
        lines.append("")
    lines.append(REST_CONTRACT)
    return "\n".join(lines).rstrip() + "\n"


def write_contract(path: Path = CONTRACT_PATH) -> None:
    path.write_text(generate_contract(), encoding="utf-8")
