"""Feature 008: publish builds, check runs, publishes, files, exports, configs, terms notes.

008 FTASKS 4.2; FTDD 008 sections 4.1, 4.6. "The database refuses what the service refuses":

- ``dw_publishes``: one non-terminal publish per repository (partial unique index; EC-7); a row
  that reached a terminal status never changes; no row is ever deleted (the publication record);
- ``dw_publish_files``: insert-only (the per-file evidence of FR-008.23);
- ``dw_publish_check_runs``: a completed snapshot never changes and is never deleted (FR-008.15);
- ``dw_config_versions`` and ``dw_model_terms_notes``: insert-only (FR-008.42, FR-008.60).

Renumbered 0010 -> 0011 on the rebase onto feature 003 (whose 0010 adds the operator allowlist).

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-07 07:23:01.920141
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


INSERT_ONLY = """
CREATE FUNCTION dw_insert_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is insert-only: rows are never updated or deleted (feature 008)', TG_TABLE_NAME;
END;
$$;
"""

PUBLISH_RECORD = """
CREATE FUNCTION dw_publishes_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'dw_publishes rows are never deleted: the publication record is permanent';
  END IF;
  IF OLD.status IN ('published', 'no_change', 'refused', 'verification_failed', 'failed',
                    'cancelled') THEN
    RAISE EXCEPTION 'dw_publishes row % is terminal (%) and never changes', OLD.id, OLD.status;
  END IF;
  RETURN NEW;
END;
$$;
"""

CHECK_SNAPSHOT = """
CREATE FUNCTION dw_publish_check_runs_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'dw_publish_check_runs rows are never deleted';
  END IF;
  IF OLD.completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'check run % is a completed snapshot and never changes', OLD.id;
  END IF;
  RETURN NEW;
END;
$$;
"""


def _guards() -> None:
    op.execute(INSERT_ONLY)
    op.execute(PUBLISH_RECORD)
    op.execute(CHECK_SNAPSHOT)
    for table in ("dw_publish_files", "dw_config_versions", "dw_model_terms_notes"):
        op.execute(
            f"CREATE TRIGGER {table}_insert_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION dw_insert_only()"
        )
    op.execute(
        "CREATE TRIGGER dw_publishes_guard BEFORE UPDATE OR DELETE ON dw_publishes "
        "FOR EACH ROW EXECUTE FUNCTION dw_publishes_guard()"
    )
    op.execute(
        "CREATE TRIGGER dw_publish_check_runs_guard BEFORE UPDATE OR DELETE ON "
        "dw_publish_check_runs FOR EACH ROW EXECUTE FUNCTION dw_publish_check_runs_guard()"
    )


def _drop_guards() -> None:
    for table in ("dw_publish_files", "dw_config_versions", "dw_model_terms_notes"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_insert_only ON {table}")
    op.execute("DROP TRIGGER IF EXISTS dw_publishes_guard ON dw_publishes")
    op.execute("DROP TRIGGER IF EXISTS dw_publish_check_runs_guard ON dw_publish_check_runs")
    op.execute("DROP FUNCTION IF EXISTS dw_insert_only()")
    op.execute("DROP FUNCTION IF EXISTS dw_publishes_guard()")
    op.execute("DROP FUNCTION IF EXISTS dw_publish_check_runs_guard()")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dw_config_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('plugin', sa.String(length=32), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_by_origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("body_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_dw_config_versions_body_sha256_pattern')),
    sa.CheckConstraint("created_by_origin IN ('operator', 'agent')", name=op.f('ck_dw_config_versions_origin_valid')),
    sa.CheckConstraint("kind IN ('selector', 'grader')", name=op.f('ck_dw_config_versions_kind_valid')),
    sa.CheckConstraint('length(created_by) > 0', name=op.f('ck_dw_config_versions_created_by_present')),
    sa.CheckConstraint('number >= 1', name=op.f('ck_dw_config_versions_number_positive')),
    sa.ForeignKeyConstraint(['parent_id'], ['dw_config_versions.id'], name=op.f('fk_dw_config_versions_parent_id_dw_config_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_config_versions')),
    sa.UniqueConstraint('kind', 'name', 'number', name='uq_dw_config_versions_kind_name_number')
    )
    op.create_table('dw_model_terms_notes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('training_on_outputs', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('noted_by', sa.Text(), nullable=False),
    sa.Column('noted_by_origin', sa.String(length=16), nullable=False),
    sa.Column('prefill_source', sa.Text(), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("noted_by_origin = 'operator'", name=op.f('ck_dw_model_terms_notes_operator_only')),
    sa.CheckConstraint("training_on_outputs IN ('permits', 'forbids')", name=op.f('ck_dw_model_terms_notes_value_valid')),
    sa.CheckConstraint('length(model_id) > 0', name=op.f('ck_dw_model_terms_notes_model_id_present')),
    sa.CheckConstraint('length(noted_by) > 0', name=op.f('ck_dw_model_terms_notes_noted_by_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_model_terms_notes'))
    )
    op.create_index('ix_dw_model_terms_notes_model', 'dw_model_terms_notes', ['model_id', sa.literal_column('noted_at DESC')], unique=False)
    op.create_table('dw_exports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=True),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('version_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('config_version_id', sa.String(length=40), nullable=True),
    sa.Column('rubric_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trl_version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('started_by_origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("started_by_origin IN ('operator', 'agent')", name=op.f('ck_dw_exports_origin_valid')),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name=op.f('ck_dw_exports_status_valid')),
    sa.CheckConstraint("target IN ('trl', 'miforge_set', 'reward_bundle')", name=op.f('ck_dw_exports_target_valid')),
    sa.CheckConstraint('length(started_by) > 0', name=op.f('ck_dw_exports_started_by_present')),
    sa.ForeignKeyConstraint(['config_version_id'], ['dw_config_versions.id'], name=op.f('fk_dw_exports_config_version_id_dw_config_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['dw_jobs.id'], name=op.f('fk_dw_exports_job_id_dw_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['dw_versions.id'], name=op.f('fk_dw_exports_version_id_dw_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_exports'))
    )
    op.create_index('ix_dw_exports_version', 'dw_exports', ['version_id'], unique=False)
    op.create_table('dw_publish_builds',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('projection_digest', sa.String(length=64), nullable=False),
    sa.Column('projection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('omitted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('started_by_origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("projection_digest ~ '^[0-9a-f]{64}$'", name=op.f('ck_dw_publish_builds_projection_digest_pattern')),
    sa.CheckConstraint("status IN ('queued', 'building', 'completed', 'failed', 'cancelled')", name=op.f('ck_dw_publish_builds_status_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['dw_jobs.id'], name=op.f('fk_dw_publish_builds_job_id_dw_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['dw_versions.id'], name=op.f('fk_dw_publish_builds_version_id_dw_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_publish_builds'))
    )
    op.create_index('ix_dw_publish_builds_version', 'dw_publish_builds', ['version_id', 'projection_digest'], unique=False)
    op.create_index('uq_dw_publish_builds_completed', 'dw_publish_builds', ['version_id', 'projection_digest'], unique=True, postgresql_where=sa.text("status = 'completed'"))
    op.create_table('dw_publish_check_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('build_id', sa.String(length=40), nullable=False),
    sa.Column('repo_id', sa.Text(), nullable=False),
    sa.Column('requested_visibility', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('licence_table_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("requested_visibility IN ('private', 'public')", name=op.f('ck_dw_publish_check_runs_visibility_valid')),
    sa.CheckConstraint("status IN ('queued', 'completed', 'failed', 'cancelled')", name=op.f('ck_dw_publish_check_runs_status_valid')),
    sa.ForeignKeyConstraint(['build_id'], ['dw_publish_builds.id'], name=op.f('fk_dw_publish_check_runs_build_id_dw_publish_builds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['dw_jobs.id'], name=op.f('fk_dw_publish_check_runs_job_id_dw_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['dw_versions.id'], name=op.f('fk_dw_publish_check_runs_version_id_dw_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_publish_check_runs'))
    )
    op.create_index('ix_dw_publish_check_runs_version', 'dw_publish_check_runs', ['version_id', 'created_at'], unique=False)
    op.create_table('dw_publishes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('build_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_publish_id', sa.String(length=40), nullable=True),
    sa.Column('repo_id', sa.Text(), nullable=False),
    sa.Column('requested_visibility', sa.String(length=16), nullable=False),
    sa.Column('visibility_after', sa.String(length=16), nullable=True),
    sa.Column('repo_existed', sa.Boolean(), nullable=True),
    sa.Column('repo_was_private', sa.Boolean(), nullable=True),
    sa.Column('head_before', sa.String(length=40), nullable=True),
    sa.Column('commit', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('card_prose', sa.Text(), nullable=False),
    sa.Column('card_sha256', sa.String(length=64), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('published_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('check_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('licence_table_version', sa.Integer(), nullable=True),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('send_id', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('started_by_origin', sa.String(length=16), nullable=False),
    sa.Column('cancel_too_late', sa.Boolean(), nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("commit IS NULL OR commit ~ '^[0-9a-f]{40}$'", name=op.f('ck_dw_publishes_commit_pattern')),
    sa.CheckConstraint("kind IN ('publish', 'card_only')", name=op.f('ck_dw_publishes_kind_valid')),
    sa.CheckConstraint("request_digest ~ '^[0-9a-f]{64}$'", name=op.f('ck_dw_publishes_request_digest_pattern')),
    sa.CheckConstraint("requested_visibility IN ('private', 'public')", name=op.f('ck_dw_publishes_visibility_valid')),
    sa.CheckConstraint("started_by_origin = 'operator' OR approval_id IS NOT NULL", name=op.f('ck_dw_publishes_agent_needs_approval')),
    sa.CheckConstraint("started_by_origin IN ('operator', 'agent')", name=op.f('ck_dw_publishes_origin_valid')),
    sa.CheckConstraint("status <> 'published' OR (commit IS NOT NULL AND published_manifest IS NOT NULL AND visibility_after IS NOT NULL)", name=op.f('ck_dw_publishes_published_is_complete')),
    sa.CheckConstraint("status IN ('queued', 'checking', 'uploading', 'verifying', 'published', 'no_change', 'refused', 'verification_failed', 'failed', 'cancelled')", name=op.f('ck_dw_publishes_status_valid')),
    sa.CheckConstraint("visibility_after IS NULL OR visibility_after IN ('private', 'public')", name=op.f('ck_dw_publishes_visibility_after_valid')),
    sa.CheckConstraint('length(started_by) > 0', name=op.f('ck_dw_publishes_started_by_present')),
    sa.ForeignKeyConstraint(['approval_id'], ['dw_approvals.id'], name=op.f('fk_dw_publishes_approval_id_dw_approvals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['build_id'], ['dw_publish_builds.id'], name=op.f('fk_dw_publishes_build_id_dw_publish_builds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['dw_jobs.id'], name=op.f('fk_dw_publishes_job_id_dw_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_publish_id'], ['dw_publishes.id'], name=op.f('fk_dw_publishes_parent_publish_id_dw_publishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['dw_versions.id'], name=op.f('fk_dw_publishes_version_id_dw_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dw_publishes'))
    )
    op.create_index('ix_dw_publishes_approval_digest', 'dw_publishes', ['approval_id', 'request_digest'], unique=False)
    op.create_index('ix_dw_publishes_repo_created', 'dw_publishes', ['repo_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dw_publishes_version', 'dw_publishes', ['version_id'], unique=False)
    op.create_index('uq_dw_publishes_active_repo', 'dw_publishes', ['repo_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'checking', 'uploading', 'verifying')"))
    op.create_table('dw_publish_files',
    sa.Column('publish_id', sa.String(length=40), nullable=False),
    sa.Column('path_in_repo', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('split', sa.Text(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('git_blob_sha1', sa.String(length=40), nullable=False),
    sa.Column('remote_lfs_sha256', sa.String(length=64), nullable=True),
    sa.Column('remote_blob_id', sa.String(length=40), nullable=True),
    sa.Column('remote_size', sa.BigInteger(), nullable=True),
    sa.Column('match', sa.Boolean(), nullable=True),
    sa.CheckConstraint("git_blob_sha1 ~ '^[0-9a-f]{40}$'", name=op.f('ck_dw_publish_files_git_blob_sha1_pattern')),
    sa.CheckConstraint("role IN ('split', 'card', 'manifest')", name=op.f('ck_dw_publish_files_role_valid')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_dw_publish_files_sha256_pattern')),
    sa.CheckConstraint('bytes >= 0', name=op.f('ck_dw_publish_files_bytes_nonnegative')),
    sa.ForeignKeyConstraint(['publish_id'], ['dw_publishes.id'], name=op.f('fk_dw_publish_files_publish_id_dw_publishes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('publish_id', 'path_in_repo', name=op.f('pk_dw_publish_files'))
    )
    # ### end Alembic commands ###
    _guards()


def downgrade() -> None:
    _drop_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dw_publish_files')
    op.drop_index('uq_dw_publishes_active_repo', table_name='dw_publishes', postgresql_where=sa.text("status IN ('queued', 'checking', 'uploading', 'verifying')"))
    op.drop_index('ix_dw_publishes_version', table_name='dw_publishes')
    op.drop_index('ix_dw_publishes_repo_created', table_name='dw_publishes')
    op.drop_index('ix_dw_publishes_approval_digest', table_name='dw_publishes')
    op.drop_table('dw_publishes')
    op.drop_index('ix_dw_publish_check_runs_version', table_name='dw_publish_check_runs')
    op.drop_table('dw_publish_check_runs')
    op.drop_index('uq_dw_publish_builds_completed', table_name='dw_publish_builds', postgresql_where=sa.text("status = 'completed'"))
    op.drop_index('ix_dw_publish_builds_version', table_name='dw_publish_builds')
    op.drop_table('dw_publish_builds')
    op.drop_index('ix_dw_exports_version', table_name='dw_exports')
    op.drop_table('dw_exports')
    op.drop_index('ix_dw_model_terms_notes_model', table_name='dw_model_terms_notes')
    op.drop_table('dw_model_terms_notes')
    op.drop_table('dw_config_versions')
    # ### end Alembic commands ###
