"""Uploads: streaming receive, sniffing, validation, conversion, content hash (FR-001.21–001.25,
001.27; 001 FTID section 3.8).

- ``receive_stream`` reads 1 MiB chunks, hashing and counting as it goes, and refuses
  ``upload_too_large`` the moment the cap is passed, removing the partial file: a cap enforced after
  the fact is a disk filled first.
- Format is sniffed from content (Parquet magic ``PAR1``; JSONL's first non-empty byte ``{``;
  otherwise CSV) and must match the extension (``upload_format_mismatch``). JSONL is checked line by
  line first so the first bad line is reported exactly (``upload_malformed``).
- A ``_dw_`` column refuses (``reserved_column``).
- ``content_hash`` = SHA-256 of the canonical JSON of the sorted ``[{split, sha256, parse_options}]``
  with CSV defaults filled in, so an omitted default and an explicit one hash the same.
- User file names are data only; every path is generated by the server.
"""

from __future__ import annotations

import json
import os
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pyarrow as pa
import pyarrow.csv as pacsv
import pyarrow.json as pajson
import pyarrow.parquet as pq

from ...core.errors import AppError
from ..identity import digest_text, new_hasher
from .hashing import hash_file

CHUNK = 1024 * 1024
BATCH_ROWS = 10_000
EXTENSIONS = {
    "parquet": {".parquet"},
    "jsonl": {".jsonl", ".json", ".ndjson"},
    "csv": {".csv", ".tsv", ".txt"},
}
CSV_DEFAULTS: dict[str, Any] = {
    "delimiter": ",",
    "quote": '"',
    "header": True,
    "encoding": "utf-8",
    "type_mode": "infer",
}


@dataclass(frozen=True)
class Received:
    path: Path
    bytes: int
    sha256: str
    original_name: str


async def receive_stream(upload: Any, destination: Path, cap: int, original_name: str) -> Received:
    """Stream one ``UploadFile`` to ``destination`` with a running hash and size cap."""
    hasher = new_hasher()
    size = 0
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(destination, "wb") as handle:
            while chunk := await upload.read(CHUNK):
                size += len(chunk)
                if size > cap:
                    raise AppError(
                        f"{original_name} is over the {cap:,}-byte upload limit. Split it, or raise the "
                        "limit in Settings → Storage.",
                        code="upload_too_large",
                        status_code=413,
                        details={"file": original_name, "limit_bytes": cap},
                    )
                hasher.update(chunk)
                handle.write(chunk)
    except BaseException:
        destination.unlink(missing_ok=True)
        raise
    return Received(destination, size, hasher.hexdigest(), original_name)


def csv_options(options: dict[str, Any] | None) -> dict[str, Any]:
    return {**CSV_DEFAULTS, **(options or {})}


def parse_options(fmt: str, csv: dict[str, Any] | None) -> dict[str, Any]:
    return {"format": fmt, **csv_options(csv)} if fmt == "csv" else {"format": fmt}


def sniff_format(path: Path) -> str:
    with open(path, "rb") as handle:
        head = handle.read(4096)
    if head[:4] == b"PAR1":
        return "parquet"
    stripped = head.lstrip()
    return "jsonl" if stripped[:1] == b"{" else "csv"


def check_extension(name: str, fmt: str) -> None:
    ext = os.path.splitext(name)[1].lower()
    if ext and ext not in EXTENSIONS[fmt]:
        raise AppError(
            f"{name} looks like {fmt} inside but its name says {ext}. Rename it or check the file.",
            code="upload_format_mismatch",
            status_code=422,
            details={"file": name, "sniffed": fmt},
        )


def check_jsonl(path: Path, name: str) -> None:
    with open(path, encoding="utf-8", errors="strict") as handle:
        for number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError:
                value = None
            if not isinstance(value, dict):
                raise AppError(
                    f"Line {number} of {name} is not a JSON object.",
                    code="upload_malformed",
                    status_code=422,
                    details={"file": name, "line": number},
                )


def _refuse_reserved(columns: list[str], name: str) -> None:
    reserved = [c for c in columns if c.startswith("_dw_")]
    if reserved:
        raise AppError(
            f"{name} has a column {reserved[0]!r}; the _dw_ prefix is reserved. Rename it and upload again.",
            code="reserved_column",
            status_code=422,
            details={"file": name, "column": reserved[0]},
        )


def _csv_options(options: dict[str, Any], bad_rows: list[int]) -> tuple[Any, Any, Any]:
    def on_invalid(row: Any) -> str:
        bad_rows.append(int(row.number) if row.number is not None else -1)
        return "error"

    # Single-threaded so a bad row carries its line number (pyarrow omits it when threaded).
    read = pacsv.ReadOptions(
        encoding=options["encoding"],
        autogenerate_column_names=not options["header"],
        use_threads=False,
    )
    parse = pacsv.ParseOptions(
        delimiter=options["delimiter"], quote_char=options["quote"], invalid_row_handler=on_invalid
    )
    convert = pacsv.ConvertOptions(strings_can_be_null=False)
    return read, parse, convert


def _batches(received: Received, fmt: str, options: dict[str, Any]) -> Iterator[pa.RecordBatch]:
    """The file as record batches. Parquet and all-text CSV are streamed; inferred-type CSV and
    JSONL are read in one piece (whole-file type inference; pyarrow's JSON reader has no
    streaming form) — tracked debt for files near the 2 GiB cap."""
    if fmt == "parquet":
        yield from pq.ParquetFile(received.path).iter_batches(batch_size=BATCH_ROWS)
        return
    if fmt == "jsonl":
        check_jsonl(received.path, received.original_name)
        yield from pajson.read_json(received.path).to_batches(max_chunksize=BATCH_ROWS)
        return
    bad_rows: list[int] = []
    read, parse, convert = _csv_options(options, bad_rows)
    try:
        if options["type_mode"] == "infer":
            # Types are inferred over the whole file: the streaming reader infers from its first
            # block only, and a later block with another type would fail as "malformed".
            table = pacsv.read_csv(
                received.path, read_options=read, parse_options=parse, convert_options=convert
            )
            yield from table.to_batches(max_chunksize=BATCH_ROWS)
            return
        names = pacsv.open_csv(received.path, read_options=read, parse_options=parse).schema.names
        as_text = pacsv.ConvertOptions(
            strings_can_be_null=False, column_types={name: pa.string() for name in names}
        )
        yield from pacsv.open_csv(
            received.path, read_options=read, parse_options=parse, convert_options=as_text
        )
    except (pa.ArrowInvalid, UnicodeDecodeError) as exc:
        line = bad_rows[0] if bad_rows else None
        where = f" at line {line}" if line and line > 0 else ""
        raise AppError(
            f"{received.original_name} is not valid CSV with these options{where}. Check the "
            "delimiter, quote and header settings.",
            code="upload_malformed",
            status_code=422,
            details={
                "file": received.original_name,
                "line": line,
                "error_type": type(exc).__name__,
            },
        ) from None


def validate_and_convert(
    received: Received, split: str, csv: dict[str, Any] | None, destination: Path
) -> dict[str, Any]:
    """Sniff, check the extension, convert in record batches with the app's writer, fsync, hash.

    Refuses ``upload_format_mismatch``, ``upload_malformed`` (with the line) and
    ``reserved_column``. Rows come from the converted file's Parquet metadata.
    """
    fmt = sniff_format(received.path)
    check_extension(received.original_name, fmt)
    options = parse_options(fmt, csv)
    destination.parent.mkdir(parents=True, exist_ok=True)
    writer: pq.ParquetWriter | None = None
    try:
        for batch in _batches(received, fmt, options):
            if writer is None:
                _refuse_reserved(batch.schema.names, received.original_name)
                writer = pq.ParquetWriter(destination, batch.schema, compression="zstd")
            writer.write_batch(batch)
        if writer is None:
            raise AppError(
                f"{received.original_name} has no rows.",
                code="upload_malformed",
                status_code=422,
                details={"file": received.original_name, "line": None},
            )
    except BaseException:
        if writer is not None:
            writer.close()
            writer = None
        destination.unlink(missing_ok=True)
        raise
    finally:
        if writer is not None:
            writer.close()
    fd = os.open(destination, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)
    meta = pq.ParquetFile(destination)
    return {
        "split": split,
        "rows": meta.metadata.num_rows,
        "bytes": destination.stat().st_size,
        "sha256": hash_file(destination),
        "columns": [{"name": f.name, "type": str(f.type)} for f in meta.schema_arrow],
        "original_name": received.original_name,
        "original_sha256": received.sha256,
        "original_bytes": received.bytes,
        "parse_options": options,
    }


def content_hash(entries: list[dict[str, Any]]) -> str:
    """Identity of an upload: independent of file order, sensitive to bytes and parse options."""
    canonical = sorted(
        (
            {"split": e["split"], "sha256": e["sha256"], "parse_options": e["parse_options"]}
            for e in entries
        ),
        key=lambda e: (e["split"], e["sha256"]),
    )
    return digest_text(canonical)
